using System.Collections.Generic;
using atelier_platform_aplicaciones_web.Shared.Domain.Model.Events;

namespace atelier_platform_aplicaciones_web.Shared.Domain.Model.Entities;

/// <summary>
///     Interface for entities that generate and hold domain events
/// </summary>
public interface IHasDomainEvents
{
    /// <summary>
    ///     Collection of domain events generated by the entity
    /// </summary>
    IReadOnlyCollection<IEvent> DomainEvents { get; }

    /// <summary>
    ///     Clears the domain events collection after they have been dispatched
    /// </summary>
    void ClearDomainEvents();
}
